[package]
name = "resources"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.0"
tonic = "0.8.0"
hyper = "0.14.23"

[build-dependencies]
tonic-build = { version = "0.8.0", features = ["prost"] }
