[package]
name = "grafana"
version = "0.1.0"
edition = "2021"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "hello-server"
path = "src/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "hello-client"
path = "src/client.rs"

[dependencies]
fregate = { path = "../.." }
tracing = "0.1.36"
tokio = { version = "1.0", features = ["full"] }
prost = "0.11.0"
tonic = "0.8.0"
opentelemetry = { version = "0.17.0", features = ["rt-tokio", "rt-async-std", "trace"]}
tracing-opentelemetry = "0.17.4"

[build-dependencies]
tonic-build = { version = "0.8.0", features = ["prost"] }
