[package]
name = "reflection"
version = "0.1.0"
edition = "2021"

[dependencies]
fregate = { path = "../.." }
resources = { path = "../examples_resources" }

tokio = { version = "1", features = ["rt-multi-thread"] }
tonic-reflection = "0.9.*"
