[package]
name = "reflection"
version = "0.1.0"
edition = "2021"

[dependencies]
fregate = { path = "../.." }
resources = { path = "../examples_resources" }
tonic-reflection = "0.5.0"
tokio = { version = "1.22.0", features = ["rt-multi-thread"] }
