[package]
name = "log-level-change"
version = "0.1.0"
edition = "2021"

[dependencies]
fregate = { path = "../.." }
tracing-subscriber = "0.3.15"
tokio = { version = "1", features = ["rt-multi-thread"] }
