[package]
name = "metrics-callback"
version = "0.1.0"
edition = "2021"

[dependencies]
fregate = { path = "../..", features = ["tokio-metrics"] }
metrics = "0.20.1"
tokio = { version = "1", features = ["rt-multi-thread"] }
