[package]
name = "configuration"
version = "0.1.0"
edition = "2021"

[dependencies]
fregate = { path = "../.." }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
