on:
  pull_request:
    branches: [ "main" ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: arduino/setup-protoc@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: arduino/setup-protoc@v1
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: arduino/setup-protoc@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: #--features native-tls

  test-native-tls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: arduino/setup-protoc@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features use_native_tls -- --ignored

  test-rustls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: arduino/setup-protoc@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features use_rustls -- --ignored
